feat: ['feature:*', 'feat:*','build:*']
fix: ['bug:*', 'bugfix:*', 'fix:*', 'revert:*']
ci: ['ci:*']
refactor: ['refactor:*']
style: ['style:*']
perf: ['perf:*']
build: ['build:*']
chore: ['chore:*']
docs: ['docs:*', 'documentation:*', 'doc:*']
test: ['test:*']
release: ['Release:*', 'BREAKING CHANGE:*']
