repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.800
    hooks:
      - id: mypy
        additional_dependencies:
          - 'pydantic'
        language_version: python3
        args:
          - --no-warn-unused-ignores
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.2
    hooks:
      - id: python-check-blanket-noqa
      - id: python-use-type-annotations
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
        additional_dependencies: [toml]
        exclude: env.py
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--line-length=120", "--target-version=py39"]
        exclude: ^(\.git/|\.idea/)

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]
