site_name: ml-restful-api-template
site_description: "ml-restful-api-template"
site_author: "Ashit, Aritra, PK"
docs_dir: docs/
repo_name: "ab-inbev-analytics/ml-restful-api-template"
repo_url: "https://github.com/ab-inbev-analytics/ml-restful-api-template"
nav:
  - 'Home': index.md
theme:
  name: "material"
  features:
    - content.code.annotate
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
plugins:
  - mkdocs-video:
      css_style:
        width: "80%"
        height: "30.172vw"
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
