name: "Update Changelog"

on:
  release:
    types: [released]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Update Changelog  
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md

      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: release.md
          write-mode: overwrite
          contents: |
            # Version: ${{ github.event.release.tag_name }}

            
            ${{ github.event.release.body }}
            
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          branch: "develop"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
